<?php
require_once "Router/connection_db.php";

/*
$create = "CREATE TABLE Register_db(
    id INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
UniqueID VARCHAR(40) NOT NULL,
Email TEXT NOT NULL,
First_name TEXT,
Last_name TEXT,
Username TEXT ,
Password VARCHAR(255) NOT NULL,
Reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
Image_path VARCHAR(255),
Ip_addr VARCHAR(40) NOT NULL,
User_agent TEXT NOT NULL
    )";*/
/*
    $create = "CREATE TABLE Auth(
        
    id INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
UniqueID VARCHAR(40) NOT NULL,
HashID VARCHAR(255) NOT NULL,
Date_added TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )";
*/
/*
$create = "CREATE TABLE Albums(
    
    id INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
UniqueID VARCHAR(40) NOT NULL,
HashID VARCHAR(255) NOT NULL,
Album_name TEXT NOT NULL,
Genre TEXT NOT NULL,
Status_mode ENUM('Private_mode','Public_mode'),
Image_path VARCHAR(255) NOT NULL,
Date_added TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
Ip VARCHAR(255) NOT NULL,
User_agent VARCHAR(255) NOT NULL
)";
*/
/*
$create = "CREATE TABLE Sound_video_db(
 id INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
UniqueID VARCHAR(40) NOT NULL,
TrackID VARCHAR(255) NOT NULL,
TrackPath VARCHAR(255) NOT NULL,
TrackName TEXT NOT NULL,
TrackArtist TEXT NOT NULL,
Album_name TEXT NOT NULL,
AlbumID VARCHAR(255) NOT NULL,
Status_mode ENUM('Private_mode','Public_mode'),
File_type ENUM('audio','video','HD') NOT NULL,
Image_path VARCHAR(255) ,
Date_added TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
Ip VARCHAR(255) NOT NULL,
User_agent VARCHAR(255) NOT NULL

)";
*/


/*
$create = "CREATE TABLE Library_playlist(
    id INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   UniqueID VARCHAR(40) NOT NULL,
   TrackID VARCHAR(255) NOT NULL,
   Date_added TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   Ip VARCHAR(255) NOT NULL,
   User_agent VARCHAR(255) NOT NULL
   
   )";
*/

/*
$create = "CREATE TABLE Like_dislike(
    id INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   UniqueID VARCHAR(40) NOT NULL,
   TrackID VARCHAR(255) NOT NULL,
   Status ENUM('LIKE','DIS_LIKE') NOT NULL,
   Date_added TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   Ip VARCHAR(255) NOT NULL,
   User_agent VARCHAR(255) NOT NULL
   )";
*/

/*

$create = "CREATE TABLE Genre_types(
    id INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   UniqueID VARCHAR(40) NOT NULL,
Types TEXT NOT NULL,
   Date_added TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   Ip VARCHAR(255) NOT NULL,
   User_agent VARCHAR(255) NOT NULL
   )";
*/

$create = "CREATE TABLE Reset_password(
    id INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   UniqueID VARCHAR(40) NOT NULL,
Types TEXT NOT NULL,
Status  ENUM('Nil','Exp') NOT NULL,
HashID VARCHAR(255) NOT NULL,
PlainID VARCHAR(255) NOT NULL,
   Date_added TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   Ip VARCHAR(255) NOT NULL,
   User_agent VARCHAR(255) NOT NULL
   )";

if(mysqli_query($conn,$create)){

    die("Table created");

}else{

    die("Failed to create table");
}